language: node_js
node_js:
  - "6"
  - "10"
cache:
  directories:
    - "node_modules"
before_script:
  - npm install grunt # fixes sails.lift() grunt error
script:
  - npm run lint
  - npm test
after_success:
  - npm run coverage
